### PR TITLE
Fix/debug modal

### PR DESCRIPTION
**Pull request by pwltr**

### CODE REVIEW

**Comment by AaronDewes** [comment]
Why did you change the linter here too?

**Comment by pwltr** [comment]
Nothing to merge yet, it's WIP. How should we go about adding & running prettier on all repos? Would be nice to do cause my editor keeps trying to format things differently. Does this config look okay to you?

**Comment by AaronDewes** [comment]
The config looks fine for me, but instead of adding prettier as a dependency & extra task, please simply pass `--prettier` to xo, it should work the same

**Comment by pwltr** [comment]
I see, didn't know xo does both. If it's okay for you I'll add this config to the other repos and run it once for the whole project. Should we add a pre-commit hook or CI action while we're at it?

**Comment by AaronDewes** [comment]
> I see, didn't know xo does both. If it's okay for you I'll add this config to the other repos and run it once for the whole project. Should we add a pre-commit hook or CI action while we're at it?

Yes, sounds good

**Comment by pwltr** [comment]
moved to https://github.com/runcitadel/manager/pull/111

**Pull request closed without merging**
